lightbody/browsermob-proxy

- src/main/java/net/lightbody/bmp/proxy/guice/ConfigModule.java
- src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHttpClient.java
- src/test/java/net/lightbody/bmp/proxy/MailingListIssuesTest.java
I noticed the uadetector library is no longer working properly because user-agent-string.info is not returning user agent info. http://user-agent-string.info redirects to http://udger.com/, so when uadetector tries to read updated user agent strings, it gets an invalid response which clears uadetector's saved cache of user agents.
Until uadetector is updated to pull user agent strings from somewhere else, I've changed the way uadetector is initialized so it only reads user agent strings from the saved resources.
> Fix for uadetector unkown user agent

- browsermob-core/src/main/java/net/lightbody/bmp/core/har/HarEntry.java
- browsermob-core/src/main/java/net/lightbody/bmp/core/json/ISO8601WithTDZDateFormatter.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/util/Base64.java
Reduces a few of the many javadoc warnings that appear when building. PR #157 will reduce a few more, but most of the remaining will have to wait until after Jetty 5 is retired.
> Minor cleanup of javadoc warnings

- browsermob-core/src/main/java/net/lightbody/bmp/proxy/BrowserMobProxyHandler.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHttpClient.java
Although seldom-used, TRACE is a valid HTTP method.
> Added seldom-used HTTP TRACE support

- browsermob-core/src/main/java/net/lightbody/bmp/core/util/ThreadUtils.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/ProxyServer.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHttpClient.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/HttpClientInterrupter.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/MailingListIssuesTest.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/TimeoutsTest.java
Modified the BrowserMobHttpClient timeout polling mechanism and the waitForNetworkTrafficToStop polling mechanisms to use ScheduledExecutorServices with a single thread.
> Threading cleanup

- browsermob-core/src/main/java/net/lightbody/bmp/proxy/BrowserMobProxyHandler.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/ErrorResponseTest.java
Returning HTTP 504 Gateway Timeout when the connection to the remote server times out. 504 better matches the HTTP status code definition:
`The server, while acting as a gateway or proxy, did not receive a timely response from the upstream server specified by the URI (e.g. HTTP, FTP, LDAP) or some other auxiliary server (e.g. DNS) it needed to access in attempting to complete the request.`
Than 502:
`The server, while acting as a gateway or proxy, received an invalid response from the upstream server it accessed in attempting to fulfill the request.`
> HTTP 504 on connection timeout

- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHttpClient.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/util/BrowserMobProxyUtil.java
Part of a code cleanup effort to move non-proxy-related functionality out of the ProxyServer class.
> Move user agent parser to utility class

- browsermob-core/src/test/java/net/lightbody/bmp/proxy/BlackAndWhiteListTest.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/PhantomJSTest.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/RewriteRuleTest.java
Replaced junit assumptions with assertions where appropriate. Skipping PhantomJSTest on travis-ci for now.
> Minor unit test cleanup

- browsermob-core/src/main/java/net/lightbody/bmp/core/har/HarEntry.java
- browsermob-core/src/main/java/net/lightbody/bmp/core/har/HarTimings.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHostNameResolver.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHttpClient.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/RequestInfo.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/SimulatedSocket.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/TrustingSSLSocketFactory.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/HarTest.java
This PR fixes the SSL timing always = -1 issue with the Har. Har classes now use nanoseconds internally, which will help when testing very fast dns/connect/etc. calls.
The JSON version of the HAR continues to use milliseconds, per the HAR spec.
> Har timing fixes

- browsermob-core/src/main/java/net/lightbody/bmp/proxy/LegacyProxyServer.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/ProxyServer.java
As a step before the merge of PR #162, this PR introduces a LegacyProxyServer interface that codifies the 2.0.0 interface. There is one potentially-breaking change that may affect client code: the getWhitelistUrls() method now returns `Collection<String>` instead of `Collection<Pattern>`. This will align the LegacyProxyServer interface with the new interface defined in #162.
> LegacyProxyServer interface

- browsermob-core/pom.xml
- pom.xml
This should preserve compatibility with the latest Firefox, which was broken using Selenium 2.43.1.
> Selenium version update

- browsermob-core/src/test/java/net/lightbody/bmp/proxy/PhantomJSTest.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/test/util/ProxyServerTest.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/ProxyManager.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/bricks/ProxyResource.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/guice/ConfigModule.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/guice/LegacyProxyServerProvider.java
- browsermob-rest/src/test/java/net/lightbody/bmp/proxy/ExpiringProxyTest.java
- browsermob-rest/src/test/java/net/lightbody/bmp/proxy/ProxyPortAssignmentTest.java
- browsermob-rest/src/test/java/net/lightbody/bmp/proxy/test/util/ProxyManagerTest.java
This PR changes all existing ProxyServer references to use LegacyProxyServer, to prepare for swapping out the Jetty-based ProxyServer implementation with the upcoming LittleProxy implementation.
> Use LegacyProxyServer interface instead of ProxyServer implementation

- pom.xml
This enables using groovy to write unit tests. With the new interface now merged to master (and documentation on the way!), I'm just about ready to create a PR for the initial LittleProxy integration. I want to include several new unit tests for the new interface and new functionality before officially releasing it, and using groovy will speed up that process.
As a side effect of this, the Eclipse compiler will now compile the java source instead of javac. Practically speaking this should have no effect whatsoever.
> Enable groovy unit tests

- browsermob-core/pom.xml
The selenium-api dependency can be made optional to reduce the size of the release package, as well as to exclude unused code when not using BMP in Selenium tests. Since Selenium tests will already include a dependency on selenium-api, this removal should be harmless.
> Made selenium dependency optional in browsermob-core

- browsermob-core-littleproxy/pom.xml
- browsermob-core/pom.xml
- pom.xml
This should reduce unnecessary dependencies when using only the LittleProxy implementation. Most notably, this eliminates the dependency on servlet-api 2.5, which will avoid the servlet-api conflicts reported in issue #103 (and others).
It also bumps the netty version to 4.0.27, the latest stable version.
> Bump netty version and reduce LP implementation's transitive dependencies.

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/RequestFilterAdapter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/ResponseFilterAdapter.java
- browsermob-core-littleproxy/src/test/java/net/lightbody/bmp/proxy/InterceptorTest.java
This allows RequestFilter and ResponseFilter to fire when request/response aggregation has been disabled by setting a size of 0 for the request/response buffers. HttpMessageContents will be null when aggregation is not enabled.
> Allow addRequestFilter/addResponseFilter without aggregated messages

- browsermob-core-littleproxy/pom.xml
- browsermob-dist/pom.xml
- pom.xml
This adds com.jcraft:jzlib as a dependency, since netty (via LittleProxy) doesn't transitively include it. Thanks to Alex Johnson who reported the issue!
This PR also updates some plugin versions, and updates to the latest slf4j (should be binary compatible for projects using previous versions).
> Add deflate support

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/proxy/dns/DelegatingHostResolver.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/NewHarTest.groovy
- browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxy.java
- browsermob-core/src/main/java/net/lightbody/bmp/client/ClientUtil.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/ProxyServer.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/dns/BasicHostResolver.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/dns/DnsJavaResolver.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/dns/HostResolver.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHttpClient.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/LegacyHostResolverAdapter.java
This makes AdvancedHostResolver the only used supported by the BrowserMobProxy interface. This eliminates the need to cast to AdvancedHostResolver when attempting to use the cache-manipulating and other features of the built-in resolvers after calling BrowserMobProxy.getHostNameResolver().
This PR also makes the native JDK resolver the default resolver in the LittleProxy implementation and disables dnsjava by default. The legacy implementation continues to use dnsjava with native fallback by default.
> HostResolver updates

- README.md
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsAwareFiltersAdapter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/RequestFilterAdapter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/ResponseFilterAdapter.java
- browsermob-core-littleproxy/src/test/java/net/lightbody/bmp/proxy/InterceptorTest.java
- browsermob-core/src/main/java/net/lightbody/bmp/filters/RequestFilter.java
- browsermob-core/src/main/java/net/lightbody/bmp/filters/ResponseFilter.java
- browsermob-core/src/main/java/net/lightbody/bmp/util/HttpMessageInfo.java
- browsermob-rest/src/main/java/net/lightbody/bmp/exception/JavascriptCompilationException.java
- browsermob-rest/src/main/java/net/lightbody/bmp/filters/JavascriptRequestResponseFilter.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/bricks/ProxyResource.java
- browsermob-rest/src/test/groovy/net/lightbody/bmp/proxy/FilterTest.groovy
This PR replaces the originalRequest parameter on the RequestFilter and ResponseFilter with a new object, HttpMessageInfo. The new object provides access to the originalRequest, as well as an isHttps() method, the full URL (of the original request), and the client's ChannelHandlerContext.
The main motivator for this change was a recognition that we will want to expose additional data to the filters in the future. If we add them as interface parameters, the interface will become unmanageable, and every change will break all existing code. By placing these additional message parameters into an object, we can continue to add fields over time without breaking existing code.
Major thanks to @NozomiIto for bringing this issue to light in issue #238!
> Replaced originalRequest on filters with new HttpMessageInfo object

- browsermob-core-littleproxy/pom.xml
This will force the netty version of projects that depend on BMP (unless the user explicitly overrides it, of course).
> Added explicit netty dependency to browsermob-core-littleproxy

- browsermob-dist/src/main/java/net/lightbody/bmp/proxy/Main.java
- pom.xml
This resolves a minor issue where standalone mode would result in a MalformedURLException on Windows.
> Avoid MalformedURLException on Windows

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/BlacklistFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/BrowserMobHttpFilterChain.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/WhitelistFilter.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/BlacklistTest.groovy
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/NewHarTest.groovy
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/WhitelistTest.groovy
This should fix an issue with blacklist and whitelist responses under LittleProxy. Since the BMP build of LittleProxy does not automatically close short-circuit responses from the black/whitelists, we need to explicitly set the Content Length so clients can detect the end of the message.
> Blacklist & whitelist hanging response fix

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/BrowserMobHttpFilterChain.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/ModifiedRequestAwareFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/RequestFilterAdapter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/ResponseFilterAdapter.java
- browsermob-core-littleproxy/src/test/java/net/lightbody/bmp/proxy/InterceptorTest.java
- browsermob-core/src/main/java/net/lightbody/bmp/util/HttpMessageInfo.java
This PR exposes the actual URL, as modified by filters, to HttpMessageInfo. This should make adding multiple filters more convenient, since they will be able to see modifications to requests performed by previous filters.
> Added modified url to HttpMessageInfo

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/BlacklistFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsAwareFiltersAdapter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/WhitelistFilter.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/BlacklistTest.groovy
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/WhitelistTest.groovy
- browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxy.java
This PR makes whitelist and blacklist pattern matching consistent across HTTP and HTTPS calls. Blacklist and whitelist entries will match the entire URL, including scheme, host, and port.
All HTTP CONNECTs are now automatically whitelisted and cannot be short-circuited using the whitelist response code.
> Fixed blacklist and whitelist url pattern matching

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/BrowserMobHttpFilterChain.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/ssl/BrowserMobProxyMitmManager.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/NewHarTest.groovy
- browsermob-core/src/main/java/net/lightbody/bmp/core/har/HarResponse.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/BrowserTest.java
- pom.xml
This PR addresses issue #207 for HTTP requests. I'll submit a future PR for HTTPS requests, which are trickier because BMP does not have access to the "real" request, only the CONNECT.
> Add HAR error capture for HTTP requests

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/BrowserMobHttpFilterChain.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/FilterChainTest.groovy
This PR suppresses (but logs) exceptions thrown from filters in the filter chain, to prevent requests from being aborted.
> Not aborting requests when filter in filter chain throws exception

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/BrowserMobHttpFilterChain.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpConnectHarCaptureFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsConnectHarCaptureFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/ResolvedHostnameCacheFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/support/HttpConnectTiming.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/util/HarCaptureUtil.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/NewHarTest.groovy
- browsermob-core-littleproxy/src/test/java/net/lightbody/bmp/proxy/InterceptorTest.java
- browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxy.java
As promised in #274, this PR adds HAR error capture for HTTP CONNECT failures. If an HTTP CONNECT fails due to dns failure, connection timeout, or response timeout, it will create an entry in the HAR indicating the reason for failure.
> Add HAR error capture for HTTPS requests

- pom.xml
This PR updates to the latest LittleProxy, which should bring in a fix to the regression noted in #212.
> Update to latest bmp littleproxy build

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/NewHarTest.groovy
This PR changes the HAR capture behavior so that it always captures mimeType, even when the response content capture type is disabled. Also, it now captures the literal Content-Type header from the request (previously it would sometimes mangle it). When response content capture is enabled, the response.content.size field will be populated as well.
This should address issue #286.
> Fix mimeType and size capture in response.content HAR object

- browsermob-core/src/main/java/net/lightbody/bmp/proxy/dns/AbstractHostNameRemapper.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/dns/AdvancedHostResolver.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/dns/AdvancedHostResolverTest.java
This PR fixes an exception that occurred when attempting to remap a host that had already been remapped. If a remapping already exists, calling remapHost() now removes the existing remapping and appends the new remapping to the end of the remapped hosts list.
> Allow replacing existing remappings

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/NewHarTest.groovy
- browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxy.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/ProxyServer.java
This adds some convenience methods to make setting HAR capture types a bit more intuitive. For example:
```java
proxy.enableHarCaptureTypes(CaptureType.REQUEST_HEADERS, CaptureType.REQUEST_CONTENT);
```
> Add friendlier varargs options for setHarCaptureTypes()

- browsermob-core-littleproxy/pom.xml
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/util/BrowserMobHttpUtilTest.groovy
- browsermob-core/src/main/java/net/lightbody/bmp/exception/UnsupportedCharsetException.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/CaptureType.java
- browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobHttpUtil.java
- browsermob-core/src/main/java/net/lightbody/bmp/util/HttpMessageContents.java
- browsermob-core/src/main/java/net/lightbody/bmp/util/HttpObjectUtil.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/bricks/ProxyResource.java
This PR removes the Apache httpmime dependency when using the LittleProxy implementation. It also cleans up the Content-Type header parsing, especially when determining charsets. The proxy now handles unsupported charsets in a more reasonable manner.
> Remove Apache httpmime dependency from LP module

- README.md
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/guice/ConfigModule.java
Now that the LittleProxy support has matured, this PR changes the default implementation in standalone mode to LittleProxy. Legacy is still available by specifying `--use-littleproxy false`.
> Defaulting to LittleProxy-based implementation in standalone mode

- browsermob-core/src/main/java/net/lightbody/bmp/proxy/selenium/SeleniumProxyHandler.java
I am aware if the jvm exists, it will remove all created temp folders. However, I need to keep the jvm running as long as possible in production, which eventually cause the temp folder to fill up with tons of temp folders created by the proxy.
Fix: changed DeleteDirectoryTask deleteDirectoryTask to List deleteDirectoryTasks in SeleniumProxyHandler class, so that when user need to clean up the temp folders but keep the jvm running they can just call proxy.cleanSslCertificates() method.
> change deleteDirectoryTask to a List

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsAwareFiltersAdapter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsHostCaptureFilter.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/BlacklistTest.groovy
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/NewHarTest.groovy
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/util/BrowserMobHttpUtilTest.groovy
- browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobHttpUtil.java
This PR strips the default port 443 from the HTTPS URLs returned by HttpsAwareFiltersAdapter. Previously the default port (443) would be captured and stored as part of the HTTPS URL returned by the adapter, which meant blacklist entries for HTTPS requests would have to include port 443 explicitly in the regex. This change brings HTTPS matching behavior in line with existing HTTP-matching behavior.
> Stripping default port 443 from HTTPS URLs

- mitm/src/main/java/net/lightbody/bmp/mitm/util/EncryptionUtil.java
- mitm/src/test/groovy/net/lightbody/bmp/mitm/PemFileCertificateSourceTest.groovy
This PR will allow people to compile on JVMs that do not have the unlimited strength policy files installed.
> Remove test dependency on unlimited strength policy files

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/BlacklistFilter.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/BlacklistTest.groovy
This PR changes the BlacklistFilter behavior to require the HTTP method when blacklisting CONNECTs. Since the typical use case of blacklists is to blacklist requests, not the SSL negotiation process, this prevents the blacklist from interfering with the latter.
> Require HTTP method to blacklist CONNECTs

- mitm/src/main/java/net/lightbody/bmp/mitm/manager/ImpersonatingMitmManager.java
This adds a convenience method for a default ImpersonatingMitmManager that uses EC keys for the root certificate and server certificates.
> Add EC builder to ImpersonatingMitmManager

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
This PR fixes two issues: when cookie max age was not set, an invalid date would appear in the HAR file; and the arithmetic for the expiration date was incorrect.
> Fix for cookie expiration in HAR files

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/AutoBasicAuthFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsAwareFiltersAdapter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsHostCaptureFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsOriginalHostCaptureFilter.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/AutoAuthTest.groovy
- mitm/src/test/java/net/lightbody/bmp/mitm/integration/LittleProxyIntegrationTest.java
- new-interface-compatibility.md
This PR adds auto basic auth to the LP implementation, one of the last remaining features in BMP that was not implemented using LittleProxy.
As part of the auto auth implementation, this PR also contains some cleanup and fixes to HttpsAwareFiltersAdapter. Notable, the `getHostAndPort()` method has been renamed `getHost()`, since it only returned the host; and a new `getHostAndPort()` method that returns the host and port has been added.
> Add auto basic authentication to LittleProxy implementation

- .gitignore
Motivation:
* Developing BMP modules with Eclipse creates some artifacts in the modules too, which should be ignored.
Modifications:
* Added to `.gitignore` Eclipse names in first level subdirectories.
> Ignore Eclipse generated files in modules too.

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/ProxyManager.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/bricks/ProxyResource.java
This PR adds the useEcc option to BrowserMobProxyServer and the REST API. The option enables ECC using the supplied ca-certificate-ecc.cer file.
When using the REST API, add the query param useEcc=true to enable ECC by default.
> Add useEcc convenience option to BrowserMobProxyServer and REST API

- browsermob-core-littleproxy/pom.xml
- pom.xml
I'm not sure why tests pass locally for me but fail in travis-ci due to OutOfMemoryError, but giving surefire plenty of memory seems to fix the issue.
> Update surefire settings to fix travis-ci build

- mitm/src/main/java/net/lightbody/bmp/mitm/util/MitmConstants.java
SHA384 and SHA512 have the same performance characteristics on 64-bit machines.
> Using SHA384 instead of SHA512 when signing impersonated certificates

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
- browsermob-core/src/main/java/net/lightbody/bmp/core/har/HarContent.java
This fixes issue #395. response.content.mimeType is now always included in the serialized HAR, even if it is null. Additionally, a missing Content-Type header will no longer set the mimeType to null.
> Fix missing mimeType in HAR

- mitm/pom.xml
- pom.xml
This updates the LP version used by MITM to the newly-released beta2, and browsermob-core-littleproxy to the newest BMP-LP build.
> Update LittleProxy version to beta2

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpConnectHarCaptureFilter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsAwareFiltersAdapter.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/RewriteUrlFilter.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/util/BrowserMobHttpUtilTest.groovy
- browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobHttpUtil.java
- mitm/README.md
- mitm/pom.xml
- mitm/src/main/java/net/lightbody/bmp/mitm/manager/ImpersonatingMitmManager.java
- mitm/src/main/java/net/lightbody/bmp/util/HttpUtil.java
- mitm/src/test/groovy/net/lightbody/bmp/mitm/ImpersonatingMitmManagerTest.groovy
- mitm/src/test/java/net/lightbody/bmp/mitm/ImpersonationPerformanceTests.java
- pom.xml
This PR incorporates the latest fixes from LittleProxy master, one of which allows us to generate certificates for clients using the hostname included in the request, rather than the hostname of the upstream server.
Because the LP update includes a breaking change to the MitmManager class, this means the `mitm` module will not be compatible with stock littleproxy-1.1.0-beta2. Once a new LP version is released, `mitm`'s compatibility will be restored.
> Incorporate LP fixes and use client hostname when generating certificates

- mitm/src/main/java/net/lightbody/bmp/mitm/tools/BouncyCastleSecurityProviderTool.java
This PR fixes an issue where connecting to an IP address over HTTPS would cause browser security warnings because the IP address was added as a DNS Name instead of an IP Address in the SAN list.
> Properly add IP addresses to SAN list when impersonating IP address hostnames

- mitm/src/main/java/net/lightbody/bmp/mitm/trustmanager/InsecureExtendedTrustManager.java
- mitm/src/main/java/net/lightbody/bmp/mitm/trustmanager/InsecureTrustManagerFactory.java
- mitm/src/main/java/net/lightbody/bmp/mitm/util/SslUtil.java
This fixes issue #437. The trustAllServers option should now bypass all server certificate checks.
> Make trustAllServers bypass all server certificate validations

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/AutoAuthTest.groovy
- browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/ChainedProxyAuthTest.groovy
- browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxy.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/ProxyServer.java
- browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobHttpUtil.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/ProxyManager.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/bricks/ProxyResource.java
This PR enables Basic proxy authentication support in embedded mode and in standalone via the REST API.
The REST API now supports two new query params when creating a new proxy: `proxyUsername` and `proxyPassword`. If they are present, they will be used when authenticating with upstream proxies via the Proxy-Authorization header. (Note that this is a temporary solution until the new REST API is ready.)
> Add support for chained proxy authorization

- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServerLegacyAdapter.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/CookieTest.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/test/util/ProxyServerTest.java
- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/guice/LegacyProxyServerProvider.java
- browsermob-rest/src/test/groovy/net/lightbody/bmp/proxy/FilterTest.groovy
This PR removes support for the old interface (LegacyProxyServer) from the BrowserMobProxyServer class. It creates a new BrowserMobProxyServerLegacyAdapter class to implement LegacyProxyServer for legacy clients that have not yet switched to the new methods.
This is part 1 of a far-reaching restructuring in advance of 2.1.0.
> Remove support for LegacyProxyServer from the new LP implementation

- mitm/src/main/java/net/lightbody/bmp/mitm/TrustSource.java
- mitm/src/main/java/net/lightbody/bmp/mitm/util/TrustUtil.java
This PR fixes an issue that occurs when the default Java trust store contains no trusted certificate entries.
> Fix null TrustStore exception

- browsermob-core/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
- browsermob-core/src/test/groovy/net/lightbody/bmp/proxy/NewHarTest.groovy
This PR fixes the cookie capture issues reported in #311. It also updates the cookie decoding code to use Netty's new cookie decoders, instead of the deprecated decoder we had been using.
> Fix for HAR cookie capture

- browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxy.java
- browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-legacy/src/main/java/net/lightbody/bmp/BrowserMobProxyServerLegacyAdapter.java
- browsermob-legacy/src/main/java/net/lightbody/bmp/proxy/ProxyServer.java
This PR adds getter methods for bandwidth limits to the BrowserMobProxy interface. It should also fix issue #458.
> Support getting read and write bandwidth limits

- browsermob-rest/src/main/java/net/lightbody/bmp/proxy/bricks/ProxyResource.java
The captureCookies param was missing from the REST API the since the default CaptureTypes changed with 2.1.0.
> Adding missing captureCookies param to REST API

- browsermob-core/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
- browsermob-core/src/main/java/net/lightbody/bmp/filters/ResolvedHostnameCacheFilter.java
This fixes the issue reported in #484, and also fixes the IP address caching in the HarCaptureFilter, which was expiring IP addresses too soon.
> Fix IP address caching in HarCaptureFilter

- browsermob-dist/pom.xml
- pom.xml
In order to increase testing of BMP with netty 4.1, I'm setting the default netty verison in standalone mode to 4.1.
> Making netty 4.1 the default in standalone mode

- pom.xml
Netty recommends upgrading due to a memory leak, so I'll get this out there.
> Upgraded to latest netty to avoid memory leak

- browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxy.java
- browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
This PR should clarify when setChainedProxy can be called, and prevent the issue reported in #530.
> Throw exception when calling setChainedProxy without bootstrapping a ChainedProxyManager

- pom.xml
Keeping these versions up to date. Holding off on Jackson 2.8.x for now in case of any incompatibilities.
> Updated bouncycastle and jackson versions

- mitm/src/main/java/net/lightbody/bmp/mitm/trustmanager/InsecureExtendedTrustManager.java
The NOOP_EXTENDED_TRUST_MANAGER was actually null in the DEFAULT_EXTENDED_TRUST_MANAGER, since the no-op trust manager wasn't initialized until after the default trust manager.
> Reordered static final fields to avoid nulls during class initialization

- browsermob-dist/src/main/java/net/lightbody/bmp/proxy/Main.java
Adds a simple `--version` flag to the command-line to address issue #565.
> Added simple 'version' flag to command-line launcher

- browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobHttpUtil.java
This PR updates the default charset to UTF-8 rather than ISO-8859-1, which was specified in the previous HTTP spec. UTF-8 is far more common now, and if anybody is using a non-UTF-8 charset, the "should" specify the charset.
Technically this does not meet RFC 7321 Appendix B's requirement that the default in the media type definition be used; but UTF-8 is generally safe and far simpler than maintaining a list of media types and default charsets.
> Updated default charset to UTF-8

- browsermob-dist/src/main/scripts/browsermob-proxy
> Fixes for Mac OS start script

- browsermob-core/pom.xml
- browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
- browsermob-core/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
- browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobProxyUtil.java
- browsermob-legacy/src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHttpClient.java
- browsermob-legacy/src/test/java/net/lightbody/bmp/proxy/HarTest.java
This removes the dependency on uadetector, which is no longer being updated, and seems to cause more problems than it solves (e.g. #557). 
It also makes little sense for BMP to put the browser version in the HarLog object. As an alternative, the User-Agent header can be captured like any other header using the REQUEST_HEADERS CaptureType, which will also move the user agent info to the request level, which makes much more sense for BMP.
> Remove uadetector

- browsermob-core/src/main/java/net/lightbody/bmp/client/ClientUtil.java
- browsermob-core/src/main/java/net/lightbody/bmp/proxy/dns/DnsJavaResolver.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/dns/AdvancedHostResolverCacheTest.java
- browsermob-core/src/test/java/net/lightbody/bmp/proxy/dns/AdvancedHostResolverTest.java
This PR officially deprecates dnsjava support. Dnsjava usage with BMP appears to be rather low, and removing dnsjava support allows me to focus on other parts of the proxy.
dnsjava will be removed in the next significant release, either 2.2.x or 3.0.
> Deprecate dnsjava

- browsermob-core/src/test/java/net/lightbody/bmp/proxy/dns/AdvancedHostResolverCacheTest.java
Cherry-picked the DNS update from @valfirst 's PR #648.
> Use nanoseconds in dns tests

- browsermob-legacy/src/test/java/net/lightbody/bmp/proxy/HarTest.java
Inspired by @valfirst's efforts in #648, this PR removes tests in the legacy HarTest class that relied on external websites, including msn.com. Almost all of this functionality is covered by the new HAR tests in NewHarTest.
> Removed tests from legacy HarTest that used external websites
