pom.xml, src/main/java/net/lightbody/bmp/core/har/Har.java, src/main/java/net/lightbody/bmp/core/har/HarCache.java, src/main/java/net/lightbody/bmp/core/har/HarCacheStatus.java, src/main/java/net/lightbody/bmp/core/har/HarContent.java, src/main/java/net/lightbody/bmp/core/har/HarCookie.java, src/main/java/net/lightbody/bmp/core/har/HarEntry.java, src/main/java/net/lightbody/bmp/core/har/HarLog.java, src/main/java/net/lightbody/bmp/core/har/HarPage.java, src/main/java/net/lightbody/bmp/core/har/HarPageTimings.java, src/main/java/net/lightbody/bmp/core/har/HarPostData.java, src/main/java/net/lightbody/bmp/core/har/HarPostDataParam.java, src/main/java/net/lightbody/bmp/core/har/HarRequest.java, src/main/java/net/lightbody/bmp/core/har/HarResponse.java, src/main/java/net/lightbody/bmp/core/json/ISO8601DateFormatter.java, src/main/java/net/lightbody/bmp/core/json/ISO8601WithTDZDateFormatter.java, src/main/java/net/lightbody/bmp/proxy/bricks/ProxyResource.java, src/test/java/net/lightbody/bmp/proxy/HarTest.java
This upgrades to Jackson 2 and the latest sitebricks.
=> Jackson & Sitebricks upgrade

browsermob-core/pom.xml, pom.xml
Minor updates to phantomjs and pom versions. Updated phantomjs to (hopefully) avoid some tests timing out on Java 8.
=> Phantomjs & pom updates

.travis.yml, browsermob-core/src/test/java/net/lightbody/bmp/proxy/BrowserTest.java
This will enable travis-ci. Now we just need @lightbody to enable travis-ci for his fork :)
=> Enable Travis CI

browsermob-core/src/main/java/net/lightbody/bmp/proxy/selenium/SeleniumProxyHandler.java
This PR replaces FileUtils.forceDeleteOnExit(tempDir) with a nio-based FileVisitor. It seems the commons-io 2.4 implementation of forceDeleteOnExit doesn't actually delete files created in the directory after it the method was called.
=> Delete temp directories on exit

browsermob-core/src/test/java/net/lightbody/bmp/proxy/dns/ChainedHostResolverTest.java, browsermob-core/src/test/java/net/lightbody/bmp/proxy/test/util/TestConstants.java
Very minor cleanup to a unit test.
=> Minor test refactoring

README.md, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/RequestFilterAdapter.java, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/ResponseFilterAdapter.java, browsermob-core-littleproxy/src/test/java/net/lightbody/bmp/proxy/InterceptorTest.java, browsermob-core/src/main/java/net/lightbody/bmp/filters/RequestFilter.java, browsermob-core/src/main/java/net/lightbody/bmp/filters/ResponseFilter.java, browsermob-rest/pom.xml, browsermob-rest/src/main/java/net/lightbody/bmp/proxy/bricks/ProxyResource.java, browsermob-rest/src/test/groovy/net/lightbody/bmp/proxy/FilterTest.groovy
This PR adds access to the originalRequest to LP filters.
=> Add originalRequest to littleproxy filters

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java, browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobHttpUtil.java
This should fix the issues relating to non-standard query parameter decoding and malformed request URIs reported in #206 and #207.
=> Har query param and malformed URI fixes

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/ssl/BrowserMobProxyMitmManager.java, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/ssl/BrowserMobSslEngineSource.java
This should fix the issue reported in #205.
=> Do not generate new keystore file

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java
This should hopefully resolve issue #228!
=> Fixed failure to capture more than 1 POST parameter

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsAwareFiltersAdapter.java, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsHostCaptureFilter.java, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsOriginalHostCaptureFilter.java, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/RewriteUrlFilter.java, browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/NewHarTest.groovy, browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobHttpUtil.java
This PR should fix issue #227.
=> Fix for missing URL in HAR

browsermob-core-littleproxy/pom.xml, browsermob-core/pom.xml, browsermob-rest/pom.xml
Minor cleanup of netty dependencies in the test scope.
=> Netty dependency changes

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java, browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/proxy/NewHarTest.groovy, browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobHttpUtil.java
This PR should address issue #280.
=> Capture redirectURL in HAR

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/util/HarCaptureUtil.java
This PR should (hopefully) address issue #285.
=> Always populating HarResponse when a new HarRequest is created

browsermob-core-littleproxy/pom.xml, browsermob-core/src/test/java/net/lightbody/bmp/proxy/BrowserTest.java, browsermob-core/src/test/resources/log4j2-test.json, browsermob-dist/pom.xml, browsermob-rest/pom.xml, browsermob-rest/src/test/resources/log4j2-test.json, pom.xml
Several updates to various dependencies and plugins.
=> Dependency updates

browsermob-core-littleproxy/src/test/java/net/lightbody/bmp/proxy/InterceptorTest.java, browsermob-rest/pom.xml, pom.xml
This also updates a few other unit test dependencies.
=> Update to HttpClient 4.5

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
This PR provides wrapper methods to expose LittleProxy's chained proxy manager and thread pool configuration.
=> Expose chained proxy and thread pool configuration in LP module

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsAwareFiltersAdapter.java, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/RewriteUrlFilter.java, browsermob-core-littleproxy/src/test/groovy/net/lightbody/bmp/util/BrowserMobHttpUtilTest.groovy, browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobHttpUtil.java
This is actually PR #371 with a few code style changes.
=> Not escaping URL paths when applying rewrite rules

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HttpsAwareFiltersAdapter.java, browsermob-core/src/main/java/net/lightbody/bmp/util/BrowserMobHttpUtil.java
This should fix issue #378, as well as the issue in PR #393.
=> Fix for duplicate scheme in HAR due to invalid characters in URI 

README.md, browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java, browsermob-core/src/main/java/net/lightbody/bmp/proxy/ProxyServer.java
Doc updates for the beta 5 release, and a slightly-too-late update to the HAR version string.
=> Beta 5 documentation updates

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java, browsermob-core/pom.xml, browsermob-core/src/main/java/net/lightbody/bmp/proxy/ProxyServer.java, browsermob-core/src/main/java/net/lightbody/bmp/proxy/util/BrowserMobProxyUtil.java, browsermob-core/src/main/resources/net/lightbody/bmp/version, browsermob-core/src/main/resources/version.prop, browsermob-dist/src/main/java/net/lightbody/bmp/proxy/Main.java
Finally pulling the HAR creator version string from the version file, which will prevent it from getting out-of-sync again (as it was for the last release).
=> Using automatic version string in HAR version field

browsermob-core/src/main/java/net/lightbody/bmp/proxy/util/BrowserMobProxyUtil.java
Updating the version parsing to use the new ClasspathResourceUtil class.
=> Using new ClasspathResourceUtil when parsing version file

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java, browsermob-core/src/main/java/net/lightbody/bmp/proxy/util/IOUtils.java, browsermob-dist/pom.xml, pom.xml
Minor updates to some of the dependencies and plugins, plus very minor code cleanup.
=> Dependency updates and cleanup

browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java
The recent LP updates make this possible. This should fix issue #414.
=> Allow changing the connect timeout after the proxy has been started

README.md
Change to table-style REST API doc.
=> REST API in table

mitm/README.md, mitm/pom.xml
Minor documentation and pom updates for the new LittleProxy 1.1.0 release.
=> MITM documentation updates

browsermob-core/src/main/java/net/lightbody/bmp/filters/HttpConnectHarCaptureFilter.java
=> Fix IP address caching in HttpConnectHarCaptureFilter

browsermob-core/src/main/java/net/lightbody/bmp/filters/ServerResponseCaptureFilter.java
This should fix the immediate cause of the NPE in #492, although it does not fix the potentially larger problem of HttpResponse, HttpContent, and LastHttpContent objects being processed by the filters potentially out-of-order due to filter processing time, JVM thread scheduling, etc.
=> Fixed potential NPE in ServerResponseCaptureFilter

browsermob-rest/src/main/java/net/lightbody/bmp/proxy/ProxyManager.java, browsermob-rest/src/main/java/net/lightbody/bmp/proxy/bricks/ProxyResource.java
=> Add support for serverBindAddress in the REST API

pom.xml
Includes some minor LP bugfixes
=> Update to the latest LP release

.travis.yml, pom.xml
Updating in advance of a release.
=> Updated netty, bouncycastle, and log4j versions
